IF EXIST "../synth" rmdir /S /Q "../synth"

IF EXIST tmp rmdir /S /Q tmp
IF EXIST _xmsgs rmdir /S /Q _xmsgs
IF EXIST xlnx_auto_0_xdb rmdir /S /Q xlnx_auto_0_xdb

IF EXIST ise_flow_results.txt del /F /Q ise_flow_results.txt
IF EXIST top.syr del /F /Q top.syr
IF EXIST top.ngc del /F /Q top.ngc
IF EXIST top.ngr del /F /Q top.ngr
IF EXIST top_xst.xrpt del /F /Q top_xst.xrpt
IF EXIST top.bld del /F /Q top.bld
IF EXIST top.ngd del /F /Q top.ngd
IF EXIST top_ngdbuild.xrpt del /F /Q top_ngdbuild.xrpt
IF EXIST top_map.map del /F /Q top_map.map
IF EXIST top_map.mrp del /F /Q top_map.mrp
IF EXIST top_map.ngm del /F /Q top_map.ngm
IF EXIST top.pcf del /F /Q top.pcf
IF EXIST top_map.ncd del /F /Q top_map.ncd
IF EXIST top_map.xrpt del /F /Q top_map.xrpt
IF EXIST top_summary.xml del /F /Q top_summary.xml
IF EXIST top_usage.xml del /F /Q top_usage.xml
IF EXIST top.ncd del /F /Q top.ncd
IF EXIST top.par del /F /Q top.par
IF EXIST top.xpi del /F /Q top.xpi
IF EXIST top.ptwx del /F /Q top.ptwx
IF EXIST top.pad del /F /Q top.pad
IF EXIST top.unroutes del /F /Q top.unroutes
IF EXIST top_pad.csv del /F /Q top_pad.csv
IF EXIST top_pad.txt del /F /Q top_pad.txt
IF EXIST top_par.xrpt del /F /Q top_par.xrpt
IF EXIST top.twx del /F /Q top.twx
IF EXIST top.bgn del /F /Q top.bgn
IF EXIST top.twr del /F /Q top.twr
IF EXIST top.drc del /F /Q top.drc
IF EXIST top_bitgen.xwbt del /F /Q top_bitgen.xwbt
IF EXIST top.bit del /F /Q top.bit
IF EXIST top.lso del /F /Q top.lso
IF EXIST usage_statistics_webtalk.html del /F /Q usage_statistics_webtalk.html
IF EXIST webtalk.log del /F /Q webtalk.log
IF EXIST par_usage_statistics.html del /F /Q par_usage_statistics.html
IF EXIST ise_flow_results.txt del /F /Q ise_flow_results.txt
